import type { NextPage } from "next";
import Head from "next/head";
import { Features, HeroSection } from "../components";
import FAQ from "../components/indexPage/FAQ";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const hello = trpc.useQuery(["example.hello", { text: "from tRPC" }]);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-[calc(-320px_+_100vh)] h-auto w-full text-white text-base duration-500 transition-all ">
        <HeroSection />
        <Features />
        <FAQ />
      </main>
    </>
  );
};

export default Home;
